// <auto-generated />
namespace SistemaFacturacionInventario.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class sp_userwithroles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sp_userwithroles));
        
        string IMigrationMetadata.Id
        {
            get { return "201707151905386_sp_userwithroles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
