// <auto-generated />
namespace SistemaFacturacionInventario.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class trigger_DetallePedidos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(trigger_DetallePedidos));
        
        string IMigrationMetadata.Id
        {
            get { return "201708081759570_trigger_DetallePedidos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
